export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REFRESH_DATA = "REFRESH_DATA";
export const SET_DATA = "SET_DATA";
export const SET_CURRENT_IMAGES = "SET_CURRENT_IMAGES";
export const REFRESH_HEROES = "REFRESH_HEROES";
